<?php
/**
 * ProductsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use AuraHistoria\PartnerConnect\InternalApi\ApiException;
use AuraHistoria\PartnerConnect\InternalApi\Configuration;
use AuraHistoria\PartnerConnect\InternalApi\FormDataProcessor;
use AuraHistoria\PartnerConnect\InternalApi\HeaderSelector;
use AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * ProductsApi Class Doc Comment
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        "putPartnerProducts" => ["application/json"],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0,
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation putPartnerProducts
     *
     * Batch upsert products (Partner API)
     *
     * @param  string $shop_id Unique identifier of the partner shop (required)
     * @param  \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductData[] $put_product_data Array of products to upsert. Must not be empty. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPartnerProducts'] to see the possible values for this operation
     *
     * @throws \AuraHistoria\PartnerConnect\InternalApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError
     */
    public function putPartnerProducts(
        $shop_id,
        $put_product_data,
        string $contentType = self::contentTypes["putPartnerProducts"][0],
    ) {
        [$response] = $this->putPartnerProductsWithHttpInfo(
            $shop_id,
            $put_product_data,
            $contentType,
        );
        return $response;
    }

    /**
     * Operation putPartnerProductsWithHttpInfo
     *
     * Batch upsert products (Partner API)
     *
     * @param  string $shop_id Unique identifier of the partner shop (required)
     * @param  \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductData[] $put_product_data Array of products to upsert. Must not be empty. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPartnerProducts'] to see the possible values for this operation
     *
     * @throws \AuraHistoria\PartnerConnect\InternalApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError|\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function putPartnerProductsWithHttpInfo(
        $shop_id,
        $put_product_data,
        string $contentType = self::contentTypes["putPartnerProducts"][0],
    ) {
        $request = $this->putPartnerProductsRequest(
            $shop_id,
            $put_product_data,
            $contentType,
        );

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                // phpcs:disable WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes runtime request diagnostics.
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()
                        ? (string) $e->getResponse()->getBody()
                        : null,
                );
                // phpcs:enable WordPress.Security.EscapeOutput.ExceptionNotEscaped
            } catch (ConnectException $e) {
                // phpcs:disable WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes runtime connection diagnostics.
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null,
                );
                // phpcs:enable WordPress.Security.EscapeOutput.ExceptionNotEscaped
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse",
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                // phpcs:disable WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes the request URI for diagnostics.
                throw new ApiException(
                    sprintf(
                        "[%d] Error connecting to the API (%s)",
                        $statusCode,
                        (string) $request->getUri(),
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody(),
                );
                // phpcs:enable WordPress.Security.EscapeOutput.ExceptionNotEscaped
            }

            return $this->handleResponseWithDataType(
                "\AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse",
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        "\AuraHistoria\PartnerConnect\InternalApi\Model\ApiError",
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation putPartnerProductsAsync
     *
     * Batch upsert products (Partner API)
     *
     * @param  string $shop_id Unique identifier of the partner shop (required)
     * @param  \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductData[] $put_product_data Array of products to upsert. Must not be empty. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPartnerProducts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPartnerProductsAsync(
        $shop_id,
        $put_product_data,
        string $contentType = self::contentTypes["putPartnerProducts"][0],
    ) {
        return $this->putPartnerProductsAsyncWithHttpInfo(
            $shop_id,
            $put_product_data,
            $contentType,
        )->then(function ($response) {
            return $response[0];
        });
    }

    /**
     * Operation putPartnerProductsAsyncWithHttpInfo
     *
     * Batch upsert products (Partner API)
     *
     * @param  string $shop_id Unique identifier of the partner shop (required)
     * @param  \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductData[] $put_product_data Array of products to upsert. Must not be empty. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPartnerProducts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPartnerProductsAsyncWithHttpInfo(
        $shop_id,
        $put_product_data,
        string $contentType = self::contentTypes["putPartnerProducts"][0],
    ) {
        $returnType =
            "\AuraHistoria\PartnerConnect\InternalApi\Model\PutProductsResponse";
        $request = $this->putPartnerProductsRequest(
            $shop_id,
            $put_product_data,
            $contentType,
        );

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === "\SplFileObject") {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== "string") {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize(
                            $content,
                            $returnType,
                            [],
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    // phpcs:disable WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes the request URI for diagnostics.
                    throw new ApiException(
                        sprintf(
                            "[%d] Error connecting to the API (%s)",
                            $statusCode,
                            $exception->getRequest()->getUri(),
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody(),
                    );
                    // phpcs:enable WordPress.Security.EscapeOutput.ExceptionNotEscaped
                },
            );
    }

    /**
     * Create request for operation 'putPartnerProducts'
     *
     * @param  string $shop_id Unique identifier of the partner shop (required)
     * @param  \AuraHistoria\PartnerConnect\InternalApi\Model\PutProductData[] $put_product_data Array of products to upsert. Must not be empty. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPartnerProducts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putPartnerProductsRequest(
        $shop_id,
        $put_product_data,
        string $contentType = self::contentTypes["putPartnerProducts"][0],
    ) {
        // verify the required parameter 'shop_id' is set
        if (
            $shop_id === null ||
            (is_array($shop_id) && count($shop_id) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shop_id when calling putPartnerProducts',
            );
        }

        // verify the required parameter 'put_product_data' is set
        if (
            $put_product_data === null ||
            (is_array($put_product_data) && count($put_product_data) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $put_product_data when calling putPartnerProducts',
            );
        }

        $resourcePath = "/api/v1/shops/{shopId}/products";
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = "";
        $multipart = false;

        // path params
        if ($shop_id !== null) {
            $resourcePath = str_replace(
                "{shopId}",
                ObjectSerializer::toPathValue($shop_id),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ["application/json", "application/problem+json"],
            $contentType,
            $multipart,
        );

        // for model (json/xml)
        if (isset($put_product_data)) {
            if (
                stripos($headers["Content-Type"], "application/json") !== false
            ) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(
                    ObjectSerializer::sanitizeForSerialization(
                        $put_product_data,
                    ),
                );
            } else {
                $httpBody = $put_product_data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue)
                        ? $formParamValue
                        : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            "name" => $formParamName,
                            "contents" => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (
                stripos($headers["Content-Type"], "application/json") !== false
            ) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix("x-api-key");
        if ($apiKey !== null) {
            $headers["x-api-key"] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders["User-Agent"] = $this->config->getUserAgent();
        }

        $headers = array_merge($defaultHeaders, $headerParams, $headers);

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            "PUT",
            $operationHost . $resourcePath . ($query ? "?{$query}" : ""),
            $headers,
            $httpBody,
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen -- Guzzle debug mode requires a native stream resource.
            $options[RequestOptions::DEBUG] = fopen(
                $this->config->getDebugFile(),
                "a",
            );
            if (!$options[RequestOptions::DEBUG]) {
                // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes the configured debug file path.
                throw new \RuntimeException(
                    "Failed to open the debug file: " .
                        $this->config->getDebugFile(),
                );
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if ($dataType === "\SplFileObject") {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== "string") {
                try {
                    $content = json_decode(
                        $content,
                        false,
                        512,
                        JSON_THROW_ON_ERROR,
                    );
                } catch (\JsonException $exception) {
                    // phpcs:disable WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Generated client exception message includes the request URI for diagnostics.
                    throw new ApiException(
                        sprintf(
                            "Error JSON decoding server response (%s)",
                            $request->getUri(),
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content,
                    );
                    // phpcs:enable WordPress.Security.EscapeOutput.ExceptionNotEscaped
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0] . "00");
        $right = (int) ($rangeCode[0] . "99");

        return $statusCode >= $left && $statusCode <= $right;
    }
}
