<?php
/**
 * ContinentData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * ContinentData Class Doc Comment
 *
 * @category Class
 * @description Continent derived from a structured-address country code.
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContinentData
{
    /**
     * Possible values of this enum
     */
    public const AFRICA = 'AFRICA';

    public const ANTARCTICA = 'ANTARCTICA';

    public const ASIA = 'ASIA';

    public const EUROPE = 'EUROPE';

    public const NORTH_AMERICA = 'NORTH_AMERICA';

    public const OCEANIA = 'OCEANIA';

    public const SOUTH_AMERICA = 'SOUTH_AMERICA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AFRICA,
            self::ANTARCTICA,
            self::ASIA,
            self::EUROPE,
            self::NORTH_AMERICA,
            self::OCEANIA,
            self::SOUTH_AMERICA
        ];
    }
}


