<?php
/**
 * CurrencyData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * CurrencyData Class Doc Comment
 *
 * @category Class
 * @description Supported currencies (ISO 4217 codes): - EUR: Euro - GBP: British Pound - USD: US Dollar - AUD: Australian Dollar - CAD: Canadian Dollar - NZD: New Zealand Dollar - CNY: Chinese Yuan - BRL: Brazilian Real - PLN: Polish Złoty - TRY: Turkish Lira - JPY: Japanese Yen - CZK: Czech Koruna - RUB: Russian Ruble - AED: UAE Dirham - SAR: Saudi Riyal - HKD: Hong Kong Dollar - SGD: Singapore Dollar - CHF: Swiss Franc
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CurrencyData
{
    /**
     * Possible values of this enum
     */
    public const EUR = 'EUR';

    public const GBP = 'GBP';

    public const USD = 'USD';

    public const AUD = 'AUD';

    public const CAD = 'CAD';

    public const NZD = 'NZD';

    public const CNY = 'CNY';

    public const BRL = 'BRL';

    public const PLN = 'PLN';

    public const _TRY = 'TRY';

    public const JPY = 'JPY';

    public const CZK = 'CZK';

    public const RUB = 'RUB';

    public const AED = 'AED';

    public const SAR = 'SAR';

    public const HKD = 'HKD';

    public const SGD = 'SGD';

    public const CHF = 'CHF';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EUR,
            self::GBP,
            self::USD,
            self::AUD,
            self::CAD,
            self::NZD,
            self::CNY,
            self::BRL,
            self::PLN,
            self::_TRY,
            self::JPY,
            self::CZK,
            self::RUB,
            self::AED,
            self::SAR,
            self::HKD,
            self::SGD,
            self::CHF
        ];
    }
}


