<?php
/**
 * GetShopData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;

use \ArrayAccess;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * GetShopData Class Doc Comment
 *
 * @category Class
 * @description Complete shop information including metadata
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetShopData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'GetShopData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'shop_id' => 'string',
        'shop_slug_id' => 'string',
        'name' => 'string',
        'shop_type' => '\AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData',
        'domains' => 'string[]',
        'shopify_domain' => 'string',
        'shopify_currency' => '\AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData',
        'shopify_language' => '\AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData',
        'woocommerce_currency' => '\AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData',
        'woocommerce_language' => '\AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData',
        'url' => 'string',
        'view_url' => 'string',
        'image' => 'string',
        'structured_address' => '\AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData',
        'geo_address' => '\AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData',
        'phone' => 'string',
        'email' => 'string',
        'partner_status' => '\AuraHistoria\PartnerConnect\InternalApi\Model\ShopPartnerStatusData',
        'created' => '\DateTime',
        'updated' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'shop_id' => 'uuid',
        'shop_slug_id' => null,
        'name' => null,
        'shop_type' => null,
        'domains' => null,
        'shopify_domain' => null,
        'shopify_currency' => null,
        'shopify_language' => null,
        'woocommerce_currency' => null,
        'woocommerce_language' => null,
        'url' => 'uri',
        'view_url' => 'uri',
        'image' => 'uri',
        'structured_address' => null,
        'geo_address' => null,
        'phone' => null,
        'email' => 'email',
        'partner_status' => null,
        'created' => 'date-time',
        'updated' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'shop_id' => false,
        'shop_slug_id' => false,
        'name' => false,
        'shop_type' => false,
        'domains' => false,
        'shopify_domain' => true,
        'shopify_currency' => true,
        'shopify_language' => true,
        'woocommerce_currency' => true,
        'woocommerce_language' => true,
        'url' => true,
        'view_url' => true,
        'image' => true,
        'structured_address' => false,
        'geo_address' => false,
        'phone' => false,
        'email' => false,
        'partner_status' => false,
        'created' => false,
        'updated' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shop_id' => 'shopId',
        'shop_slug_id' => 'shopSlugId',
        'name' => 'name',
        'shop_type' => 'shopType',
        'domains' => 'domains',
        'shopify_domain' => 'shopifyDomain',
        'shopify_currency' => 'shopifyCurrency',
        'shopify_language' => 'shopifyLanguage',
        'woocommerce_currency' => 'woocommerceCurrency',
        'woocommerce_language' => 'woocommerceLanguage',
        'url' => 'url',
        'view_url' => 'viewUrl',
        'image' => 'image',
        'structured_address' => 'structuredAddress',
        'geo_address' => 'geoAddress',
        'phone' => 'phone',
        'email' => 'email',
        'partner_status' => 'partnerStatus',
        'created' => 'created',
        'updated' => 'updated'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shop_id' => 'setShopId',
        'shop_slug_id' => 'setShopSlugId',
        'name' => 'setName',
        'shop_type' => 'setShopType',
        'domains' => 'setDomains',
        'shopify_domain' => 'setShopifyDomain',
        'shopify_currency' => 'setShopifyCurrency',
        'shopify_language' => 'setShopifyLanguage',
        'woocommerce_currency' => 'setWoocommerceCurrency',
        'woocommerce_language' => 'setWoocommerceLanguage',
        'url' => 'setUrl',
        'view_url' => 'setViewUrl',
        'image' => 'setImage',
        'structured_address' => 'setStructuredAddress',
        'geo_address' => 'setGeoAddress',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'partner_status' => 'setPartnerStatus',
        'created' => 'setCreated',
        'updated' => 'setUpdated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shop_id' => 'getShopId',
        'shop_slug_id' => 'getShopSlugId',
        'name' => 'getName',
        'shop_type' => 'getShopType',
        'domains' => 'getDomains',
        'shopify_domain' => 'getShopifyDomain',
        'shopify_currency' => 'getShopifyCurrency',
        'shopify_language' => 'getShopifyLanguage',
        'woocommerce_currency' => 'getWoocommerceCurrency',
        'woocommerce_language' => 'getWoocommerceLanguage',
        'url' => 'getUrl',
        'view_url' => 'getViewUrl',
        'image' => 'getImage',
        'structured_address' => 'getStructuredAddress',
        'geo_address' => 'getGeoAddress',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'partner_status' => 'getPartnerStatus',
        'created' => 'getCreated',
        'updated' => 'getUpdated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shop_id', $data ?? [], null);
        $this->setIfExists('shop_slug_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('shop_type', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('shopify_domain', $data ?? [], null);
        $this->setIfExists('shopify_currency', $data ?? [], null);
        $this->setIfExists('shopify_language', $data ?? [], null);
        $this->setIfExists('woocommerce_currency', $data ?? [], null);
        $this->setIfExists('woocommerce_language', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('view_url', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('structured_address', $data ?? [], null);
        $this->setIfExists('geo_address', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('partner_status', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shop_id'] === null) {
            $invalidProperties[] = "'shop_id' can't be null";
        }
        if ($this->container['shop_slug_id'] === null) {
            $invalidProperties[] = "'shop_slug_id' can't be null";
        }
        if (!preg_match("/^[a-z0-9]+(-[a-z0-9]+)*$/", $this->container['shop_slug_id'])) {
            $invalidProperties[] = "invalid value for 'shop_slug_id', must be conform to the pattern /^[a-z0-9]+(-[a-z0-9]+)*$/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['shop_type'] === null) {
            $invalidProperties[] = "'shop_type' can't be null";
        }
        if ($this->container['domains'] === null) {
            $invalidProperties[] = "'domains' can't be null";
        }
        if ((count($this->container['domains']) > 100)) {
            $invalidProperties[] = "invalid value for 'domains', number of items must be less than or equal to 100.";
        }

        if ((count($this->container['domains']) < 1)) {
            $invalidProperties[] = "invalid value for 'domains', number of items must be greater than or equal to 1.";
        }

        if ($this->container['partner_status'] === null) {
            $invalidProperties[] = "'partner_status' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['updated'] === null) {
            $invalidProperties[] = "'updated' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shop_id
     *
     * @return string
     */
    public function getShopId()
    {
        return $this->container['shop_id'];
    }

    /**
     * Sets shop_id
     *
     * @param string $shop_id Unique identifier of the shop
     *
     * @return self
     */
    public function setShopId($shop_id)
    {
        if (is_null($shop_id)) {
            throw new \InvalidArgumentException('non-nullable shop_id cannot be null');
        }
        $this->container['shop_id'] = $shop_id;

        return $this;
    }

    /**
     * Gets shop_slug_id
     *
     * @return string
     */
    public function getShopSlugId()
    {
        return $this->container['shop_slug_id'];
    }

    /**
     * Sets shop_slug_id
     *
     * @param string $shop_slug_id Human-readable slug identifier of the shop (kebab-case, derived from shop name). Example: \"tech-store-premium\" or \"christies\"
     *
     * @return self
     */
    public function setShopSlugId($shop_slug_id)
    {
        if (is_null($shop_slug_id)) {
            throw new \InvalidArgumentException('non-nullable shop_slug_id cannot be null');
        }

        if ((!preg_match("/^[a-z0-9]+(-[a-z0-9]+)*$/", ObjectSerializer::toString($shop_slug_id)))) {
            throw new \InvalidArgumentException("invalid value for \$shop_slug_id when calling GetShopData., must conform to the pattern /^[a-z0-9]+(-[a-z0-9]+)*$/.");
        }

        $this->container['shop_slug_id'] = $shop_slug_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Display name of the shop
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling GetShopData., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets shop_type
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData
     */
    public function getShopType()
    {
        return $this->container['shop_type'];
    }

    /**
     * Sets shop_type
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData $shop_type shop_type
     *
     * @return self
     */
    public function setShopType($shop_type)
    {
        if (is_null($shop_type)) {
            throw new \InvalidArgumentException('non-nullable shop_type cannot be null');
        }
        $this->container['shop_type'] = $shop_type;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return string[]
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param string[] $domains All known domains associated with the shop. Domains are normalized (lowercase, no scheme, no www prefix, no path/query/fragment).
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (is_null($domains)) {
            throw new \InvalidArgumentException('non-nullable domains cannot be null');
        }

        if ((count($domains) > 100)) {
            throw new \InvalidArgumentException('invalid value for $domains when calling GetShopData., number of items must be less than or equal to 100.');
        }
        if ((count($domains) < 1)) {
            throw new \InvalidArgumentException('invalid length for $domains when calling GetShopData., number of items must be greater than or equal to 1.');
        }
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets shopify_domain
     *
     * @return string|null
     */
    public function getShopifyDomain()
    {
        return $this->container['shopify_domain'];
    }

    /**
     * Sets shopify_domain
     *
     * @param string|null $shopify_domain Optional normalized Shopify storefront domain associated with the shop. Used by the backend to match Shopify product lifecycle events to the shop. Normalized with the same rules as `domains` (lowercase, no scheme, no `www.` prefix, no path/query/fragment).
     *
     * @return self
     */
    public function setShopifyDomain($shopify_domain)
    {
        if (is_null($shopify_domain)) {
            array_push($this->openAPINullablesSetToNull, 'shopify_domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopify_domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shopify_domain'] = $shopify_domain;

        return $this;
    }

    /**
     * Gets shopify_currency
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null
     */
    public function getShopifyCurrency()
    {
        return $this->container['shopify_currency'];
    }

    /**
     * Sets shopify_currency
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null $shopify_currency Optional Shopify currency configured for the shop, serialized as an ISO 4217 code.
     *
     * @return self
     */
    public function setShopifyCurrency($shopify_currency)
    {
        if (is_null($shopify_currency)) {
            array_push($this->openAPINullablesSetToNull, 'shopify_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopify_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shopify_currency'] = $shopify_currency;

        return $this;
    }

    /**
     * Gets shopify_language
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData|null
     */
    public function getShopifyLanguage()
    {
        return $this->container['shopify_language'];
    }

    /**
     * Sets shopify_language
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData|null $shopify_language Optional Shopify default language configured for the shop. Relevant for shops using Shopify partner-shop ingestion. When present, Shopify product lifecycle events for this shop are ingested using this language. When absent, Shopify product lifecycle events for this shop currently fail instead of inferring or defaulting a language.
     *
     * @return self
     */
    public function setShopifyLanguage($shopify_language)
    {
        if (is_null($shopify_language)) {
            array_push($this->openAPINullablesSetToNull, 'shopify_language');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopify_language', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shopify_language'] = $shopify_language;

        return $this;
    }

    /**
     * Gets woocommerce_currency
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null
     */
    public function getWoocommerceCurrency()
    {
        return $this->container['woocommerce_currency'];
    }

    /**
     * Sets woocommerce_currency
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null $woocommerce_currency Optional WooCommerce currency configured for webhook-ingested products, serialized as an ISO 4217 code. When WooCommerce webhooks send a non-empty `price`, the backend parses that amount in this currency.
     *
     * @return self
     */
    public function setWoocommerceCurrency($woocommerce_currency)
    {
        if (is_null($woocommerce_currency)) {
            array_push($this->openAPINullablesSetToNull, 'woocommerce_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('woocommerce_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['woocommerce_currency'] = $woocommerce_currency;

        return $this;
    }

    /**
     * Gets woocommerce_language
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData|null
     */
    public function getWoocommerceLanguage()
    {
        return $this->container['woocommerce_language'];
    }

    /**
     * Sets woocommerce_language
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\LanguageData|null $woocommerce_language Optional WooCommerce default language configured for the shop. Relevant for shops using `POST /api/v1/webhooks/woocommerce/{shopId}`. When present, WooCommerce webhook-ingested products for this shop are ingested using this language. When absent, WooCommerce webhook requests for this shop currently fail instead of inferring or defaulting a language.
     *
     * @return self
     */
    public function setWoocommerceLanguage($woocommerce_language)
    {
        if (is_null($woocommerce_language)) {
            array_push($this->openAPINullablesSetToNull, 'woocommerce_language');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('woocommerce_language', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['woocommerce_language'] = $woocommerce_language;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url Optional primary URL of the shop website.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets view_url
     *
     * @return string|null
     */
    public function getViewUrl()
    {
        return $this->container['view_url'];
    }

    /**
     * Sets view_url
     *
     * @param string|null $view_url Optional tracked or affiliate URL derived from `url` for user-facing navigation. When the shop has a primary `url`, the backend may populate this field with either Aura Historia tracking parameters or an affiliate-link target.
     *
     * @return self
     */
    public function setViewUrl($view_url)
    {
        if (is_null($view_url)) {
            array_push($this->openAPINullablesSetToNull, 'view_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('view_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['view_url'] = $view_url;

        return $this;
    }

    /**
     * Gets image
     *
     * @return string|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string|null $image Optional URL to the shop's logo or image
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            array_push($this->openAPINullablesSetToNull, 'image');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets structured_address
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null
     */
    public function getStructuredAddress()
    {
        return $this->container['structured_address'];
    }

    /**
     * Sets structured_address
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null $structured_address structured_address
     *
     * @return self
     */
    public function setStructuredAddress($structured_address)
    {
        if (is_null($structured_address)) {
            throw new \InvalidArgumentException('non-nullable structured_address cannot be null');
        }
        $this->container['structured_address'] = $structured_address;

        return $this;
    }

    /**
     * Gets geo_address
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData|null
     */
    public function getGeoAddress()
    {
        return $this->container['geo_address'];
    }

    /**
     * Sets geo_address
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData|null $geo_address geo_address
     *
     * @return self
     */
    public function setGeoAddress($geo_address)
    {
        if (is_null($geo_address)) {
            throw new \InvalidArgumentException('non-nullable geo_address cannot be null');
        }
        $this->container['geo_address'] = $geo_address;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Optional public contact phone number of the shop.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Optional public contact email address of the shop.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets partner_status
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\ShopPartnerStatusData
     */
    public function getPartnerStatus()
    {
        return $this->container['partner_status'];
    }

    /**
     * Sets partner_status
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\ShopPartnerStatusData $partner_status partner_status
     *
     * @return self
     */
    public function setPartnerStatus($partner_status)
    {
        if (is_null($partner_status)) {
            throw new \InvalidArgumentException('non-nullable partner_status cannot be null');
        }
        $this->container['partner_status'] = $partner_status;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created When the shop was first created (RFC3339 format)
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param \DateTime $updated When the shop was last updated (RFC3339 format)
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


