<?php
/**
 * LanguageData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * LanguageData Class Doc Comment
 *
 * @category Class
 * @description Supported language codes (ISO 639-1 canonical values): - de: German (includes de-DE, de-AT, de-CH, de-LU, de-LI) - en: English (includes en-US, en-GB, en-AU, en-CA, en-NZ, and backend-specific accepted alias en_IE) - fr: French (includes fr-FR, fr-CA, fr-BE, fr-CH, fr-LU) - es: Spanish (includes es-ES, es-MX, es-AR, es-CO, es-CL, es-PE, es-VE) - it: Italian (includes it-IT, it-CH) - zh: Chinese (Simplified) (includes zh-CN, zh-Hans) - pt: Portuguese (includes pt-PT, pt-BR) - pl: Polish (includes pl-PL) - tr: Turkish (includes tr-TR) - nl: Dutch (includes nl-NL, nl-BE) - cs: Czech (includes cs-CZ) - ja: Japanese (includes ja-JP) - ru: Russian (includes ru-RU) - ar: Arabic (includes ar-SA, ar-EG, ar-AE)  &#x60;de&#x60;, &#x60;en&#x60;, &#x60;fr&#x60;, &#x60;es&#x60;, and &#x60;it&#x60; are fully supported localization/translation-target languages. &#x60;zh&#x60;, &#x60;pt&#x60;, &#x60;pl&#x60;, &#x60;tr&#x60;, &#x60;nl&#x60;, &#x60;cs&#x60;, &#x60;ja&#x60;, &#x60;ru&#x60;, and &#x60;ar&#x60; are ingestion-only languages: they can appear in stored/native content and are accepted anywhere &#x60;LanguageData&#x60; is used, but backend-generated translations and fallback localized strings are not produced in these languages.
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LanguageData
{
    /**
     * Possible values of this enum
     */
    public const DE = 'de';

    public const EN = 'en';

    public const FR = 'fr';

    public const ES = 'es';

    public const IT = 'it';

    public const ZH = 'zh';

    public const PT = 'pt';

    public const PL = 'pl';

    public const TR = 'tr';

    public const NL = 'nl';

    public const CS = 'cs';

    public const JA = 'ja';

    public const RU = 'ru';

    public const AR = 'ar';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DE,
            self::EN,
            self::FR,
            self::ES,
            self::IT,
            self::ZH,
            self::PT,
            self::PL,
            self::TR,
            self::NL,
            self::CS,
            self::JA,
            self::RU,
            self::AR
        ];
    }
}


