<?php
/**
 * PatchShopData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;

use \ArrayAccess;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * PatchShopData Class Doc Comment
 *
 * @category Class
 * @description Partial update for a shop. Only the fields present in the request body are applied; omitted or &#x60;null&#x60; fields are left unchanged. All fields are optional, so &#x60;{}&#x60; is accepted as a no-op update when sent as the JSON request body.
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchShopData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PatchShopData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'shop_type' => '\AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData',
        'domains' => 'string[]',
        'shopify_domain' => 'string',
        'shopify_currency' => '\AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData',
        'woocommerce_webhook_secret' => 'string',
        'woocommerce_currency' => '\AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData',
        'url' => 'string',
        'image' => 'string',
        'structured_address' => '\AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData',
        'phone' => 'string',
        'email' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'shop_type' => null,
        'domains' => null,
        'shopify_domain' => null,
        'shopify_currency' => null,
        'woocommerce_webhook_secret' => null,
        'woocommerce_currency' => null,
        'url' => 'uri',
        'image' => 'uri',
        'structured_address' => null,
        'phone' => null,
        'email' => 'email'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'shop_type' => true,
        'domains' => true,
        'shopify_domain' => true,
        'shopify_currency' => true,
        'woocommerce_webhook_secret' => true,
        'woocommerce_currency' => true,
        'url' => true,
        'image' => true,
        'structured_address' => true,
        'phone' => true,
        'email' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shop_type' => 'shopType',
        'domains' => 'domains',
        'shopify_domain' => 'shopifyDomain',
        'shopify_currency' => 'shopifyCurrency',
        'woocommerce_webhook_secret' => 'woocommerceWebhookSecret',
        'woocommerce_currency' => 'woocommerceCurrency',
        'url' => 'url',
        'image' => 'image',
        'structured_address' => 'structuredAddress',
        'phone' => 'phone',
        'email' => 'email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shop_type' => 'setShopType',
        'domains' => 'setDomains',
        'shopify_domain' => 'setShopifyDomain',
        'shopify_currency' => 'setShopifyCurrency',
        'woocommerce_webhook_secret' => 'setWoocommerceWebhookSecret',
        'woocommerce_currency' => 'setWoocommerceCurrency',
        'url' => 'setUrl',
        'image' => 'setImage',
        'structured_address' => 'setStructuredAddress',
        'phone' => 'setPhone',
        'email' => 'setEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shop_type' => 'getShopType',
        'domains' => 'getDomains',
        'shopify_domain' => 'getShopifyDomain',
        'shopify_currency' => 'getShopifyCurrency',
        'woocommerce_webhook_secret' => 'getWoocommerceWebhookSecret',
        'woocommerce_currency' => 'getWoocommerceCurrency',
        'url' => 'getUrl',
        'image' => 'getImage',
        'structured_address' => 'getStructuredAddress',
        'phone' => 'getPhone',
        'email' => 'getEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shop_type', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('shopify_domain', $data ?? [], null);
        $this->setIfExists('shopify_currency', $data ?? [], null);
        $this->setIfExists('woocommerce_webhook_secret', $data ?? [], null);
        $this->setIfExists('woocommerce_currency', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('structured_address', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shop_type
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData|null
     */
    public function getShopType()
    {
        return $this->container['shop_type'];
    }

    /**
     * Sets shop_type
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\ShopTypeData|null $shop_type Optional updated shop type classification.
     *
     * @return self
     */
    public function setShopType($shop_type)
    {
        if (is_null($shop_type)) {
            array_push($this->openAPINullablesSetToNull, 'shop_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shop_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shop_type'] = $shop_type;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return string[]|null
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param string[]|null $domains Optional updated set of domains for the shop. When provided, this replaces the existing domains entirely. Domains are normalized (lowercase, no scheme, no www prefix, no path/query/fragment).
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (is_null($domains)) {
            array_push($this->openAPINullablesSetToNull, 'domains');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domains', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets shopify_domain
     *
     * @return string|null
     */
    public function getShopifyDomain()
    {
        return $this->container['shopify_domain'];
    }

    /**
     * Sets shopify_domain
     *
     * @param string|null $shopify_domain Optional updated Shopify storefront domain used for Shopify partner-shop event matching. Normalized with the same rules as `domains`. When omitted or set to `null`, the current Shopify domain remains unchanged.
     *
     * @return self
     */
    public function setShopifyDomain($shopify_domain)
    {
        if (is_null($shopify_domain)) {
            array_push($this->openAPINullablesSetToNull, 'shopify_domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopify_domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shopify_domain'] = $shopify_domain;

        return $this;
    }

    /**
     * Gets shopify_currency
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null
     */
    public function getShopifyCurrency()
    {
        return $this->container['shopify_currency'];
    }

    /**
     * Sets shopify_currency
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null $shopify_currency Optional updated Shopify currency for the shop, serialized as an ISO 4217 code. When omitted or set to `null`, the current Shopify currency remains unchanged.
     *
     * @return self
     */
    public function setShopifyCurrency($shopify_currency)
    {
        if (is_null($shopify_currency)) {
            array_push($this->openAPINullablesSetToNull, 'shopify_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopify_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shopify_currency'] = $shopify_currency;

        return $this;
    }

    /**
     * Gets woocommerce_webhook_secret
     *
     * @return string|null
     */
    public function getWoocommerceWebhookSecret()
    {
        return $this->container['woocommerce_webhook_secret'];
    }

    /**
     * Sets woocommerce_webhook_secret
     *
     * @param string|null $woocommerce_webhook_secret Optional replacement WooCommerce webhook secret used to validate HMAC signatures on `POST /api/v1/webhooks/woocommerce/{shopId}`. When omitted or set to `null`, the current webhook secret remains unchanged. This field is write-only and is never returned by read responses.
     *
     * @return self
     */
    public function setWoocommerceWebhookSecret($woocommerce_webhook_secret)
    {
        if (is_null($woocommerce_webhook_secret)) {
            array_push($this->openAPINullablesSetToNull, 'woocommerce_webhook_secret');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('woocommerce_webhook_secret', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['woocommerce_webhook_secret'] = $woocommerce_webhook_secret;

        return $this;
    }

    /**
     * Gets woocommerce_currency
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null
     */
    public function getWoocommerceCurrency()
    {
        return $this->container['woocommerce_currency'];
    }

    /**
     * Sets woocommerce_currency
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\CurrencyData|null $woocommerce_currency Optional updated WooCommerce currency for the shop, serialized as an ISO 4217 code. When omitted or set to `null`, the current WooCommerce currency remains unchanged. This currency is used when WooCommerce webhook payloads provide a non-empty `price`.
     *
     * @return self
     */
    public function setWoocommerceCurrency($woocommerce_currency)
    {
        if (is_null($woocommerce_currency)) {
            array_push($this->openAPINullablesSetToNull, 'woocommerce_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('woocommerce_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['woocommerce_currency'] = $woocommerce_currency;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url Optional updated primary URL of the shop website. When omitted or set to `null`, the current URL remains unchanged.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets image
     *
     * @return string|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string|null $image Optional updated URL to the shop's logo or image. When omitted or set to `null`, the current image is left unchanged.
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            array_push($this->openAPINullablesSetToNull, 'image');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets structured_address
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null
     */
    public function getStructuredAddress()
    {
        return $this->container['structured_address'];
    }

    /**
     * Sets structured_address
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null $structured_address Optional updated structured postal address. When provided with at least one non-empty component, the backend geocodes it and refreshes `geoAddress`. When omitted or set to `null`, the current address remains unchanged.
     *
     * @return self
     */
    public function setStructuredAddress($structured_address)
    {
        if (is_null($structured_address)) {
            array_push($this->openAPINullablesSetToNull, 'structured_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('structured_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['structured_address'] = $structured_address;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Optional updated public contact phone number. When omitted or set to `null`, the current phone number remains unchanged.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Optional updated public contact email address. When omitted or set to `null`, the current email address remains unchanged.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


