<?php
/**
 * ProductStateData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * ProductStateData Class Doc Comment
 *
 * @category Class
 * @description Current state of the product: - LISTED: Product has been listed - AVAILABLE: Product is available for purchase - RESERVED: Product is reserved by a buyer - SOLD: Product has been sold - REMOVED: Product has been removed and can no longer be tracked - UNKNOWN: Product has an unknown state
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductStateData
{
    /**
     * Possible values of this enum
     */
    public const LISTED = 'LISTED';

    public const AVAILABLE = 'AVAILABLE';

    public const RESERVED = 'RESERVED';

    public const SOLD = 'SOLD';

    public const REMOVED = 'REMOVED';

    public const UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LISTED,
            self::AVAILABLE,
            self::RESERVED,
            self::SOLD,
            self::REMOVED,
            self::UNKNOWN
        ];
    }
}


