<?php
/**
 * PutProductData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;

use \ArrayAccess;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * PutProductData Class Doc Comment
 *
 * @category Class
 * @description Data for upserting a single product via the partner batch-upsert endpoint. Only &#x60;shopsProductId&#x60; is required. All other fields are optional.  During later asynchronous ingestion: - If the product **does not yet exist**, it is created using all provided fields.   Omitting &#x60;title&#x60;, &#x60;url&#x60;, or &#x60;state&#x60; will result in placeholder defaults being applied   internally (empty title, a placeholder URL, and &#x60;LISTED&#x60; state respectively). - If the product **already exists**, only &#x60;state&#x60; and &#x60;price&#x60; are updated; all other   fields are ignored for the update path.  to &#x60;UNKNOWN&#x60; when omitted.
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PutProductData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PutProductData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'shops_product_id' => 'string',
        'title' => '\AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData',
        'description' => '\AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData',
        'price' => '\AuraHistoria\PartnerConnect\InternalApi\Model\PriceData',
        'price_estimate_min' => '\AuraHistoria\PartnerConnect\InternalApi\Model\PriceData',
        'price_estimate_max' => '\AuraHistoria\PartnerConnect\InternalApi\Model\PriceData',
        'state' => '\AuraHistoria\PartnerConnect\InternalApi\Model\ProductStateData',
        'url' => 'string',
        'images' => 'string[]',
        'auction_start' => '\DateTime',
        'auction_end' => '\DateTime',
        'seller_name' => 'string',
        'structured_address' => '\AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData',
        'geo_address' => '\AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'shops_product_id' => null,
        'title' => null,
        'description' => null,
        'price' => null,
        'price_estimate_min' => null,
        'price_estimate_max' => null,
        'state' => null,
        'url' => 'uri',
        'images' => 'uri',
        'auction_start' => 'date-time',
        'auction_end' => 'date-time',
        'seller_name' => null,
        'structured_address' => null,
        'geo_address' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'shops_product_id' => false,
        'title' => true,
        'description' => true,
        'price' => true,
        'price_estimate_min' => true,
        'price_estimate_max' => true,
        'state' => true,
        'url' => true,
        'images' => true,
        'auction_start' => true,
        'auction_end' => true,
        'seller_name' => true,
        'structured_address' => true,
        'geo_address' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shops_product_id' => 'shopsProductId',
        'title' => 'title',
        'description' => 'description',
        'price' => 'price',
        'price_estimate_min' => 'priceEstimateMin',
        'price_estimate_max' => 'priceEstimateMax',
        'state' => 'state',
        'url' => 'url',
        'images' => 'images',
        'auction_start' => 'auctionStart',
        'auction_end' => 'auctionEnd',
        'seller_name' => 'sellerName',
        'structured_address' => 'structuredAddress',
        'geo_address' => 'geoAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shops_product_id' => 'setShopsProductId',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'price' => 'setPrice',
        'price_estimate_min' => 'setPriceEstimateMin',
        'price_estimate_max' => 'setPriceEstimateMax',
        'state' => 'setState',
        'url' => 'setUrl',
        'images' => 'setImages',
        'auction_start' => 'setAuctionStart',
        'auction_end' => 'setAuctionEnd',
        'seller_name' => 'setSellerName',
        'structured_address' => 'setStructuredAddress',
        'geo_address' => 'setGeoAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shops_product_id' => 'getShopsProductId',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'price' => 'getPrice',
        'price_estimate_min' => 'getPriceEstimateMin',
        'price_estimate_max' => 'getPriceEstimateMax',
        'state' => 'getState',
        'url' => 'getUrl',
        'images' => 'getImages',
        'auction_start' => 'getAuctionStart',
        'auction_end' => 'getAuctionEnd',
        'seller_name' => 'getSellerName',
        'structured_address' => 'getStructuredAddress',
        'geo_address' => 'getGeoAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shops_product_id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('price_estimate_min', $data ?? [], null);
        $this->setIfExists('price_estimate_max', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('auction_start', $data ?? [], null);
        $this->setIfExists('auction_end', $data ?? [], null);
        $this->setIfExists('seller_name', $data ?? [], null);
        $this->setIfExists('structured_address', $data ?? [], null);
        $this->setIfExists('geo_address', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shops_product_id'] === null) {
            $invalidProperties[] = "'shops_product_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shops_product_id
     *
     * @return string
     */
    public function getShopsProductId()
    {
        return $this->container['shops_product_id'];
    }

    /**
     * Sets shops_product_id
     *
     * @param string $shops_product_id The shop's own identifier for the product. Must be unique within the shop.
     *
     * @return self
     */
    public function setShopsProductId($shops_product_id)
    {
        if (is_null($shops_product_id)) {
            throw new \InvalidArgumentException('non-nullable shops_product_id cannot be null');
        }
        $this->container['shops_product_id'] = $shops_product_id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData|null $title Optional localized title for the product. Used only when creating a new product.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\LocalizedTextData|null $description Optional localized description of the product. Used only when creating a new product.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null $price Optional asking price for the product. Applied on both create and update paths.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            array_push($this->openAPINullablesSetToNull, 'price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets price_estimate_min
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null
     */
    public function getPriceEstimateMin()
    {
        return $this->container['price_estimate_min'];
    }

    /**
     * Sets price_estimate_min
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null $price_estimate_min Optional lower bound of the estimated price range. Used only when creating a new product.
     *
     * @return self
     */
    public function setPriceEstimateMin($price_estimate_min)
    {
        if (is_null($price_estimate_min)) {
            array_push($this->openAPINullablesSetToNull, 'price_estimate_min');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_estimate_min', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['price_estimate_min'] = $price_estimate_min;

        return $this;
    }

    /**
     * Gets price_estimate_max
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null
     */
    public function getPriceEstimateMax()
    {
        return $this->container['price_estimate_max'];
    }

    /**
     * Sets price_estimate_max
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\PriceData|null $price_estimate_max Optional upper bound of the estimated price range. Used only when creating a new product.
     *
     * @return self
     */
    public function setPriceEstimateMax($price_estimate_max)
    {
        if (is_null($price_estimate_max)) {
            array_push($this->openAPINullablesSetToNull, 'price_estimate_max');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_estimate_max', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['price_estimate_max'] = $price_estimate_max;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\ProductStateData|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\ProductStateData|null $state Optional product state. Applied on both create and update paths.
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url URL to the product on the shop's website. Used only when creating a new product.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets images
     *
     * @return string[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param string[]|null $images List of image URLs for the product. Used only when creating a new product.
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            array_push($this->openAPINullablesSetToNull, 'images');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('images', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets auction_start
     *
     * @return \DateTime|null
     */
    public function getAuctionStart()
    {
        return $this->container['auction_start'];
    }

    /**
     * Sets auction_start
     *
     * @param \DateTime|null $auction_start RFC3339 timestamp of when the auction for this product starts. Only relevant for auction-house shop types. Used only when creating a new product.
     *
     * @return self
     */
    public function setAuctionStart($auction_start)
    {
        if (is_null($auction_start)) {
            array_push($this->openAPINullablesSetToNull, 'auction_start');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auction_start', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auction_start'] = $auction_start;

        return $this;
    }

    /**
     * Gets auction_end
     *
     * @return \DateTime|null
     */
    public function getAuctionEnd()
    {
        return $this->container['auction_end'];
    }

    /**
     * Sets auction_end
     *
     * @param \DateTime|null $auction_end RFC3339 timestamp of when the auction for this product ends. Only relevant for auction-house shop types. Used only when creating a new product.
     *
     * @return self
     */
    public function setAuctionEnd($auction_end)
    {
        if (is_null($auction_end)) {
            array_push($this->openAPINullablesSetToNull, 'auction_end');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auction_end', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auction_end'] = $auction_end;

        return $this;
    }

    /**
     * Gets seller_name
     *
     * @return string|null
     */
    public function getSellerName()
    {
        return $this->container['seller_name'];
    }

    /**
     * Sets seller_name
     *
     * @param string|null $seller_name Optional raw name of the secondary seller for this product. Only applicable for `AUCTION_PLATFORM` and `MARKETPLACE` shop types. When provided, the backend resolves the seller shop by this name and associates the product with that seller. When omitted, or when the shop type is neither `AUCTION_PLATFORM` nor `MARKETPLACE`, the partner shop itself is used as the seller. Used only when creating a new product.
     *
     * @return self
     */
    public function setSellerName($seller_name)
    {
        if (is_null($seller_name)) {
            array_push($this->openAPINullablesSetToNull, 'seller_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seller_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seller_name'] = $seller_name;

        return $this;
    }

    /**
     * Gets structured_address
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null
     */
    public function getStructuredAddress()
    {
        return $this->container['structured_address'];
    }

    /**
     * Sets structured_address
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\StructuredAddressData|null $structured_address Optional structured address to attach to the product for geo-aware indexing and search. Used only when creating a new product.
     *
     * @return self
     */
    public function setStructuredAddress($structured_address)
    {
        if (is_null($structured_address)) {
            array_push($this->openAPINullablesSetToNull, 'structured_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('structured_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['structured_address'] = $structured_address;

        return $this;
    }

    /**
     * Gets geo_address
     *
     * @return \AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData|null
     */
    public function getGeoAddress()
    {
        return $this->container['geo_address'];
    }

    /**
     * Sets geo_address
     *
     * @param \AuraHistoria\PartnerConnect\InternalApi\Model\GeoAddressData|null $geo_address Optional coordinates to attach to the product for geo-aware indexing and search. Used only when creating a new product.
     *
     * @return self
     */
    public function setGeoAddress($geo_address)
    {
        if (is_null($geo_address)) {
            array_push($this->openAPINullablesSetToNull, 'geo_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('geo_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['geo_address'] = $geo_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


