<?php
/**
 * ShopTypeData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aura-Historia Backend API
 *
 * REST API for the Aura-Historia backend.  The backend is written in Rust and utilizes event-driven architecture with CQRS and Event-Sourcing, hosted entirely on AWS using services like API Gateway, OpenSearch, DynamoDB, SQS, and Lambda.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuraHistoria\PartnerConnect\InternalApi\Model;
use \AuraHistoria\PartnerConnect\InternalApi\ObjectSerializer;

/**
 * ShopTypeData Class Doc Comment
 *
 * @category Class
 * @description Type of vendor or shop: - AUCTION_HOUSE: Auction house selling items through auctions - AUCTION_PLATFORM: Auction platform hosting auctions for auction-houses - COMMERCIAL_DEALER: Commercial dealer or shop selling items directly - MARKETPLACE: Marketplace platform connecting buyers and sellers
 * @package  AuraHistoria\PartnerConnect\InternalApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShopTypeData
{
    /**
     * Possible values of this enum
     */
    public const AUCTION_HOUSE = 'AUCTION_HOUSE';

    public const AUCTION_PLATFORM = 'AUCTION_PLATFORM';

    public const COMMERCIAL_DEALER = 'COMMERCIAL_DEALER';

    public const MARKETPLACE = 'MARKETPLACE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUCTION_HOUSE,
            self::AUCTION_PLATFORM,
            self::COMMERCIAL_DEALER,
            self::MARKETPLACE
        ];
    }
}


